import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { AlertCircle, Bot, Code2, Loader2, Sparkles, X } from 'lucide-react';

const sections = [
  { key: 'logicAnalysis', label: 'Logic Analysis' },
  { key: 'potentialBugs', label: 'Potential Bugs' },
  { key: 'timeComplexity', label: 'Time Complexity' },
  { key: 'spaceComplexity', label: 'Space Complexity' },
  { key: 'optimizationSuggestions', label: 'Optimization Suggestions' },
  { key: 'edgeCases', label: 'Edge Cases' },
  { key: 'strengths', label: 'Strengths' },
  { key: 'improvements', label: 'Improvements' },
];

const getBadgeColor = (score) => {
  if (score >= 8) return 'bg-emerald-400/10 border-emerald-400/25 text-emerald-300';
  if (score >= 6) return 'bg-amber-400/10 border-amber-400/25 text-amber-300';
  return 'bg-red-400/10 border-red-400/25 text-red-300';
};

function ProgressBar({ value = 0 }) {
  const pct = Math.max(0, Math.min(100, Math.round(value * 10)));
  return (
    <div className="h-2 w-full rounded-full bg-slate-800">
      <div className="h-2 rounded-full bg-cyan-400 transition-all" style={{ width: `${pct}%` }} />
    </div>
  );
}

function AIReviewModal({ open, onClose, loading, error, reviewData, generatedAt }) {
  if (!open) return null;

  const score = typeof reviewData?.interviewReadinessScore === 'number' ? reviewData.interviewReadinessScore : (reviewData?.interviewScore || 0);
  const displayScore = Number.isFinite(score) ? Math.round((score + Number.EPSILON) * 10) / 10 : 'N/A';

  const correctness = score || 0;
  const optimization = score || 0;
  const codeQuality = score || 0;
  const edgeHandling = score || 0;

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-slate-950/80 px-3 py-3 backdrop-blur-md sm:px-4 sm:py-4 lg:items-center">
      <div className="flex max-h-[calc(100vh-1.5rem)] w-full max-w-5xl flex-col overflow-hidden rounded-3xl border border-slate-700/60 bg-slate-950 shadow-2xl shadow-black/40 sm:max-h-[calc(100vh-2rem)]">
        <div className="flex shrink-0 items-start justify-between gap-4 border-b border-slate-700/60 bg-slate-900/90 px-4 py-4 sm:px-5">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-cyan-400/10 text-cyan-300 ring-1 ring-cyan-400/20 sm:h-11 sm:w-11">
              <Bot className="h-5 w-5" />
            </div>
            <div>
              <h2 className="text-base font-black text-white sm:text-lg">AI Code Review</h2>
              <p className="text-xs text-slate-400 sm:text-sm">Senior Engineer & Technical Interviewer style feedback — concise and educational.</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-full p-2 text-slate-400 transition hover:bg-slate-800 hover:text-white"
            aria-label="Close code review modal"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-5">
          <div className="grid gap-4 lg:grid-cols-[260px_minmax(0,1fr)] xl:gap-6">
            <aside className="space-y-3 lg:sticky lg:top-0 lg:self-start">
              <div className="rounded-2xl border border-slate-700/60 bg-slate-900/70 p-4">
                <div className="mb-1 flex items-center gap-2 text-sm font-black text-cyan-300">
                  <Sparkles className="h-4 w-4" />
                  Review Summary
                </div>
                <p className="text-xs leading-5 text-slate-400">Premium-style review with concise, actionable feedback.</p>
              </div>

              <div className={`rounded-3xl border p-4 text-center sm:p-5 ${getBadgeColor(displayScore)}`}>
                <div className="text-xs font-black uppercase tracking-[0.2em] text-slate-500">Interview Readiness</div>
                <div className="mt-3 flex items-center justify-center gap-3">
                  <div className="flex h-20 w-20 items-center justify-center rounded-full border bg-transparent text-2xl font-black sm:h-24 sm:w-24">
                    {displayScore} / 10
                  </div>
                </div>
                <p className="mt-3 text-xs text-slate-300">How prepared this solution appears for an interview (1-10).</p>
              </div>

              <div className="rounded-2xl border border-slate-700/60 bg-slate-900/70 p-4 text-xs text-slate-400">
                {loading ? 'AI is reviewing your solution...' : 'Review generated by the AI reviewer.'}
              </div>
            </aside>

            <div className="flex min-h-0 flex-col rounded-3xl border border-slate-700/60 bg-slate-900/50 p-3 sm:p-4">
              <div className="mb-4 flex shrink-0 items-center justify-between gap-3 border-b border-slate-700/60 pb-3">
                <div>
                  <p className="text-xs font-black uppercase tracking-[0.2em] text-slate-500">Detailed Feedback</p>
                  <p className="text-sm text-slate-400">{generatedAt ? `Generated at ${new Date(generatedAt).toLocaleTimeString()}` : 'Your code review will appear here.'}</p>
                </div>
                <div className={`rounded-full border px-3 py-1 text-xs font-black text-cyan-300 ${loading ? 'border-cyan-400/20 bg-cyan-400/10' : 'border-slate-700/20 bg-transparent'}`}>
                  {loading ? 'AI is reviewing your solution...' : 'Ready'}
                </div>
              </div>

              <div className="min-h-0 flex-1 overflow-y-auto pr-1">
                {loading ? (
                  <div className="flex min-h-[320px] items-center justify-center">
                    <div className="flex items-center gap-3 rounded-2xl border border-slate-700/60 bg-slate-900/80 px-4 py-3 text-slate-300">
                      <Loader2 className="h-5 w-5 animate-spin text-cyan-300" />
                      AI is reviewing your solution...
                    </div>
                  </div>
                ) : error ? (
                  <div className="flex min-h-[320px] items-center justify-center">
                    <div className="max-w-md rounded-2xl border border-red-400/25 bg-red-400/10 p-4 text-center text-sm text-red-200">
                      <div className="mb-2 flex items-center justify-center gap-2 font-black text-red-100">
                        <AlertCircle className="h-4 w-4" />
                        Review failed
                      </div>
                      <p>{error}</p>
                    </div>
                  </div>
                ) : reviewData ? (
                  <div className="space-y-4">
                    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-2">
                      <div className="rounded-2xl border border-slate-700/60 bg-slate-950/70 p-4">
                        <div className="mb-2 flex items-center justify-between">
                          <div className="text-sm font-black text-slate-200">Correctness</div>
                          <div className="text-xs text-slate-400">{displayScore}/10</div>
                        </div>
                        <ProgressBar value={correctness} />
                      </div>

                      <div className="rounded-2xl border border-slate-700/60 bg-slate-950/70 p-4">
                        <div className="mb-2 flex items-center justify-between">
                          <div className="text-sm font-black text-slate-200">Optimization</div>
                          <div className="text-xs text-slate-400">{displayScore}/10</div>
                        </div>
                        <ProgressBar value={optimization} />
                      </div>

                      <div className="rounded-2xl border border-slate-700/60 bg-slate-950/70 p-4">
                        <div className="mb-2 flex items-center justify-between">
                          <div className="text-sm font-black text-slate-200">Code Quality</div>
                          <div className="text-xs text-slate-400">{displayScore}/10</div>
                        </div>
                        <ProgressBar value={codeQuality} />
                      </div>

                      <div className="rounded-2xl border border-slate-700/60 bg-slate-950/70 p-4">
                        <div className="mb-2 flex items-center justify-between">
                          <div className="text-sm font-black text-slate-200">Edge Case Handling</div>
                          <div className="text-xs text-slate-400">{displayScore}/10</div>
                        </div>
                        <ProgressBar value={edgeHandling} />
                      </div>
                    </div>

                    <div className="grid gap-3 sm:grid-cols-2 lg:gap-4">
                      {sections.map((section) => (
                        <article key={section.key} className="rounded-2xl border border-slate-700/60 bg-slate-950/70 p-4">
                          <div className="mb-2 flex items-center gap-2 text-sm font-black text-cyan-200">{section.label}</div>
                          <div className="chat-markdown text-sm leading-7 text-slate-200">
                            <ReactMarkdown remarkPlugins={[remarkGfm]}>
                              {Array.isArray(reviewData[section.key]) ? reviewData[section.key].join('\n- ') : (reviewData[section.key] || 'No feedback available.')}
                            </ReactMarkdown>
                          </div>
                        </article>
                      ))}
                    </div>
                  </div>
                ) : (
                  <div className="flex min-h-[280px] items-center justify-center text-center text-sm text-slate-500 sm:min-h-[320px]">
                    Trigger a review to get premium feedback on logic, bugs, complexity, optimization ideas, and edge cases.
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default AIReviewModal;